version = 3
final_space = true

[palette]
blue = '#8AADF4'
lavender = '#B7BDF8'
os = '#CE0056'
pink = '#F5BDE6'
text = '#494D64'
wight = '#FFFFFF'
python = '#3EB049'

blush = '#DA627D'
plum = '#9A348E'
salmon = '#FCA17D'
sky = '#86BBD8'
tan = '#CC3802'
teal = '#047E84'
teal_blue = '#33658A'
white = '#FFFFFF'

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = true

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
leading_diamond = '╭─'
template = '{{.Icon}} '
foreground = 'p:wight'
# powerline_symbol = ''
background = 'p:plum'
type = 'os'
style = 'diamond'

[[blocks.segments]]
# leading_diamond =  ''
template = "   {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ end }}"
foreground = 'p:wight'
# powerline_symbol = ''
powerline_symbol = ''
background = 'p:blush'
type = 'python'
style = 'powerline'
[blocks.segments.properties]
display_mode = "environment"
home_enabled = true
display_default = true

#
# [[blocks.segments]]
#   template = '{{ .UserName }}@{{ .HostName }}'
#   foreground = 'p:text'
#   powerline_symbol = ''
#   background = 'p:blue'
#   type = 'session'
#   style = 'diamond'

[[blocks.segments]]
template = ' {{ .Path }}'
foreground = 'p:text'
# powerline_symbol = ''
powerline_symbol = ''
background = 'p:salmon'
type = 'path'
style = 'powerline'

[blocks.segments.properties]
# folder_icon = '....'
# home_icon = ''
style = 'agnoster_full'

[[blocks.segments]]
template = ' {{ .HEAD }}'
foreground = 'p:text'
# powerline_symbol = ''
powerline_symbol = ''
background = 'p:sky'
type = 'git'
style = 'powerline'

[blocks.segments.properties]
branch_icon = ' '
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = false
fetch_upstream_icon = false
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '

[[blocks.segments]]
type = "root"
style = "plain"
background = "p:teal_blue"
foreground = "p:wight"
template = ""
#
# [[blocks.segments]]
# template = " {{reason .Code }}"
# style = 'powerline'
# powerline_symbol = ''
# background_templates = ["{{ if .Error }}p:tan{{ end }}"]
# # foreground = '#C94A16'
# type = 'status'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '╰─'
foreground = 'p:plum'
type = 'text'
style = 'plain'
