# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
	# Goto
	{ on = ["g", "v"], run = "cd ~/Videos", desc = "Go ~/Videos" },
	{ on = ["g", "m"], run = "cd ~/Music/MUSICZ", desc = "Go ~/Music/MUSICZ" },
	{ on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
]
